ChargingStationWeb/Models/ChargingStation.cs
using System.ComponentModel.DataAnnotations;

namespace ChargingStationWeb.Models
{
    public class ChargingStation
    {
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        public string Province { get; set; }
        public string Address { get; set; }
        public double Longitude { get; set; }
        public double Latitude { get; set; }
        public string Information { get; set; }
        public int TotalChargerPorts { get; set; }
    }
}

ChargingStationWeb/Models/ErrorViewModel.cs
using System;

namespace ChargingStationWeb.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ChargingStationWeb/Models/User.cs
namespace ChargingStationWeb.Models
{
    public class User
    {
        public string Username { get; set; }
        public string Password { get; set; }
        public string Role { get; set; }
        public string Token { get; set; }
    }
}

ChargingStationWeb/Models/ViewModel/IndexViewModel.cs
using System.Collections.Generic;

namespace ChargingStationWeb.Models.ViewModel
{
    public class IndexViewModel
    {
        public IEnumerable<ChargingStation> ChargingStationList { get; set; }
    }
}

ChargingStationWeb/Controllers/ChargingStationsController.cs
using ChargingStationWeb.Models;
using ChargingStationWeb.Repository.IRepository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace ChargingStationWeb.Controllers
{
    public class ChargingStationsController : Controller
    {
        readonly private IChargingStationRepository _ctRepo;
        public ChargingStationsController(IChargingStationRepository ctRepo)
        {
            _ctRepo = ctRepo;
        }

        [Authorize(Roles = "admin, user")]
        public IActionResult Index()
        {
            return View(new ChargingStation());
        }

        public async Task<IActionResult> GetAllChargingStation()
        {
            return Json(new { data = await _ctRepo.GetAllAsync(SD.ChargingStationAPIPath, HttpContext.Session.GetString("JWToken")) });
        }

        [HttpGet]
        [Authorize(Roles = "admin, user")]
        public async Task<IActionResult> Upsert(int? id)
        {
            var obj = new ChargingStation();
            if (id == null)
            {
                return View(obj);
            }

            obj = await _ctRepo.GetAsync(SD.ChargingStationAPIPath, id.GetValueOrDefault(), HttpContext.Session.GetString("JWToken"));

            if (obj == null)
            {
                return NotFound();
            }

            return View(obj);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Upsert(ChargingStation obj)
        {
            if (!ModelState.IsValid)
            {
                return View(obj);
            }

            if (obj.Id == 0)
            {
                await _ctRepo.CreateAsync(SD.ChargingStationAPIPath, obj, HttpContext.Session.GetString("JWToken"));
            }
            else
            {
                await _ctRepo.UpdateAsync(SD.ChargingStationAPIPath + obj.Id, obj, HttpContext.Session.GetString("JWToken"));
            }

            return RedirectToAction(nameof(Index));
        }

        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Delete(int id)
        {
            var status = await _ctRepo.DeleteAsync(SD.ChargingStationAPIPath, id, HttpContext.Session.GetString("JWToken"));

            if (status)
            {
                return Json(new { success = true, message = "Delete successful!" });
            }
            return Json(new { success = false, message = "Delete not successful!" });
        }
    }
}

ChargingStationWeb/Controllers/HomeController.cs
using ChargingStationWeb.Models;
using ChargingStationWeb.Models.ViewModel;
using ChargingStationWeb.Repository.IRepository;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Diagnostics;
using System.Security.Claims;
using System.Threading.Tasks;

namespace ChargingStationWeb.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IChargingStationRepository _ctRepo;
        private readonly IAccountRepository _accountRepo;

        public HomeController(ILogger<HomeController> logger, IChargingStationRepository ctRepo, IAccountRepository accountRepo)
        {
            _logger = logger;
            _ctRepo = ctRepo;
            _accountRepo = accountRepo;
        }

        public async Task<IActionResult> Index()
        {
            var listOfChargignStations = new IndexViewModel();
            listOfChargignStations.ChargingStationList = await _ctRepo.GetAllAsync(SD.ChargingStationAPIPath, HttpContext.Session.GetString("JWToken"));

            return View(listOfChargignStations);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        [HttpGet]
        public IActionResult Login()
        {
            User obj = new User();
            return View(obj);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(User obj)
        {
            var objUser = await _accountRepo.LoginAsync(SD.AccountAPIPath + "authenticate/", obj);

            if (objUser.Token is null)
            {
                TempData["alert_type"] = "failure";
                TempData["alert"] = "Incorrect username or password, please try again.";
                return View();
            }

            var identity = new ClaimsIdentity(CookieAuthenticationDefaults.AuthenticationScheme);
            identity.AddClaim(new Claim(ClaimTypes.Name, objUser.Username));
            identity.AddClaim(new Claim(ClaimTypes.Role, objUser.Role));
            var principal = new ClaimsPrincipal(identity);
            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal);

            HttpContext.Session.SetString("JWToken", objUser.Token);
            TempData["alert_type"] = "successful";
            TempData["alert"] = $"Welcome {objUser.Username}";

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Register(User obj)
        {
            var result = await _accountRepo.RegisterAsync(SD.AccountAPIPath + "register/", obj);

            if (result == false)
            {
                TempData["alert_type"] = "successful";
                TempData["alert"] = "Registration successful!";

                return RedirectToAction(nameof(Login));
            }

            TempData["alert_type"] = "failure";
            TempData["alert"] = "Registration failure!";
            return View();
        }

        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync();
            HttpContext.Session.SetString("JWToken", "");
            TempData["alert"] = null;
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public IActionResult AccessDenied()
        {
            return View();
        }
    }
}

ChargingStationWeb/Views/ChargingStations/Index.cshtml
@{
    ViewData["Title"] = "Charging Station";
}

<section class="flex-fill pt-5">
<div class="container">
    <div class="p-4 rounded">
        <div class="row align-items-center">
            <div class="col-lg-9 col-md-8 col-12">
                <h2 class="text-primary mb-0">Charging Station List</h2>
            </div>
            <div class="col-lg-3 col-md-4 col-12 text-md-end text-center mb-3 mb-md-0">
                <a asp-action="Upsert" class="btn btn-primary"><i class="fas fa-plus me-2"></i>Create New Charging Station</a>
            </div>
        </div>
        <br>
        <div class="p-3 rounded">
                <label hidden id="role_admin">@User.IsInRole("admin")</label>
                <table id="tblData" class="table table-striped table-bordered table-light">
                <thead class="table-primary">
                    <tr>
                        <th>Name</th>
                        <th>Province</th>
                        <th>Address</th>
                        <th>Total Charger Ports</th>
                        <th></th>
                    </tr>
                </thead>
            </table>
        </div>
    </div>
</div> 
</section>
@section Scripts{
        <script src="~/js/ChargingStations/index.js"></script>
}

ChargingStationWeb/Views/ChargingStations/Upsert.cshtml
@model ChargingStationWeb.Models.ChargingStation
@{
    ViewData["Title"] = "Charging Station";
    var title = "Create Charging Station";
}
<section class="flex-fill pt-5">
    <div class="container">
        <div class="row justify-content-center p-3">
            <div class="col-lg-6 col-md-8">
                <div class="card">
                    <div class="card-body">
                        @if (Model.Id != 0)
                        {
                            title = "Update Charging Station";
                            <input type="hidden"asp-for="Id"/>
                        }
                        <div class="col-12">
                            <h2 class="text-primary text-center">@title</h2>
                        </div>
                        <form method="post" asp-action="Upsert" enctype="application/x-www-form-urlencoded">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            <div class="row">                            
                                    <div class="mb-2">
                                        <div>
                                            <label asp-for="Name" class="form-label"></label>
                                            <input asp-for="Name" class="form-control" placeholder="Tên trạm sạc"/>
                                            <span asp-validation-for="Name" class="text-danger"></span>
                                        </div>
                                    </div>
                                    <div class="mb-2">
                                        <div>
                                            <label asp-for="Province" class="form-label"></label>
                                            <label hidden id="province">@Model.Province</label>
                                            <select asp-for="Province" class="form-select" id="province_selection">
                                                <option value="tỉnh thành" disabled selected>Tỉnh thành</option>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="mb-2">
                                        <div>
                                            <label asp-for="Address" class="form-label"></label>
                                            <input asp-for="Address" class="form-control"  placeholder="Địa chỉ"/>
                                            <span asp-validation-for="Address" class="text-danger"></span>
                                        </div>
                                    </div>
                                    <div class="row mb-2">
                                        <div class="col">
                                            <label asp-for="Latitude" class="form-label"></label>
                                            <input asp-for="Latitude" class="form-control"/>
                                            <span asp-validation-for="Latitude" class="text-danger"></span>
                                        </div>
                                        <div class="col">
                                            <label asp-for="Longitude" class="form-label"></label>
                                            <input asp-for="Longitude" class="form-control"/>
                                            <span asp-validation-for="Longitude" class="text-danger"></span>
                                        </div>
                                    </div>
                                    <div class="mb-2">
                                        <div>
                                            <label asp-for="TotalChargerPorts" class="form-label"></label>
                                            <input asp-for="TotalChargerPorts" class="form-control"/>
                                            <span asp-validation-for="TotalChargerPorts" class="text-danger"></span>
                                        </div>
                                    </div>
                                    <div class="mb-2">
                                        <div>
                                            <label asp-for="Information" class="form-label"></label>
                                            <textarea asp-for="Information" class="form-control" rows="3" placeholder="Thông tin thêm"></textarea>
                                            <span asp-validation-for="Information" class="text-danger"></span>
                                        </div>
                                    </div>
                                    <div class="row mb-2 justify-content-center">
                                        <div class="col-4">
                                            <button type="submit" class="btn btn-primary form-control">
                                                @((Model.Id != 0) ? "Update" : "Create")
                                            </button>
                                        </div>
                                        <div class="col-4">
                                            <a asp-action="Index" class="btn btn-success form-control">Back to List</a>
                                        </div>
                                    </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@section Scripts{
        <script src="~/js/ChargingStations/upsert.js"></script>   
}

ChargingStationWeb/Views/Home/AccessDenied.cshtml
@{
    ViewData["title"] = "Access Denied";
}


<section class="flex-fill pt-5">
    <div class="container pt-5">
        <h1 class="text-danger">Access Denied</h1>
        <h2 class="text-danger">You are not authorized for this page!</h2>
    </div>
</section>

ChargingStationWeb/Views/Home/Index.cshtml
@model ChargingStationWeb.Models.ViewModel.IndexViewModel
@{
    ViewData["Title"] = "Charging Station";
}

<section class="flex-fill pt-5">
    <div class="row g-0 h-100">
        <!-- Map -->
        <div class="col-9">
            <div id="map"></div>
        </div>
        <!-- Action -->
        <div class="col-3 pt-5 p-3">
            <div>
                <label for = "typeahead" class="h2 text-left">Hệ thống trạm sạc</label>
                <div class="input-group mb-3">
                    <input id = "typeahead" type="search" class="form-control" >
                </div>
            </div>

            <div>   
                <label for ="province_selection" class="h2 text-left">Khu vực tìm kiếm</label>
                <select id="province_selection" class="form-select" >
                    <option value="tỉnh thành">Tỉnh thành</option>
                </select>
            </div>
        </div>
    </div>
</section>

@section Scripts{
    <script src="~/js/Home/index.js"></script>   
}

ChargingStationWeb/Views/Home/Login.cshtml
@model ChargingStationWeb.Models.User
@{
    ViewData["Title"] = "Login";
}
<section class="flex-fill pt-5">
<div class="justify-content-center align-items-center">
    <div class="container">
        <div class="row d-flex justify-content-center">
            <div class="col-12 col-md-8 col-lg-4 pt-5">
                <div class="card bg-white">
                    <div class="card-body p-5">
                        <h2 class="fw-bold mb-2 text-uppercase text-center">Login</h2>
                        <p class=" mb-3">Please enter your username and password!</p>
                        <form class="mb-3 mt-md-4" method="post">
                            <div class="mb-3">
                            <label for="username" class="form-label ">Username</label>
                                <input asp-for="Username" type="text" class="form-control" id = "username" placeholder="username" required>
                            </div>
                            <div class="mb-3">
                                <label for="password" class="form-label ">Password</label>
                                <input asp-for="Password" type="password" class="form-control" id="password" placeholder="********" required>
                            </div>
                            <div class="d-grid">
                                <button class="btn btn-outline-dark" type="submit">Login</button>
                            </div>
                        </form>                      
                        <div class="p-2">
                            <p class="mb-0 text-center">Don't have an account?   <a class="text-primary fw-bold" asp-controller="Home" asp-action="Register">Sign Up</a></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<</section>

ChargingStationWeb/Views/Home/Register.cshtml
@model ChargingStationWeb.Models.User
@{
    ViewData["Title"] = "Register";
}

<section class="flex-fill pt-5">
<div class="justify-content-center align-items-center">
    <div class="container">
        <div class="row d-flex justify-content-center">
            <div class="col-12 col-md-6 col-lg-4 pt-5">
                <div class="card bg-white">
                    <div class="card-body p-5">
                        <h2 class="fw-bold mb-2 text-uppercase text-center">Register</h2>
                        <p class=" mb-3">Please enter your username and password!</p>
                        <form class="mb-3 mt-md-4" method="post" asp-action="Register" asp-controller="Home">
                            <div class="mb-3">
                                <label for="username" class="form-label ">Username</label>
                                <input  asp-for="Username" type="text" class="form-control" id = "username" placeholder="username" required>
                            </div>
                            <div class="mb-3">
                                <label for="password" class="form-label ">Password</label>
                                <input asp-for="Password" type="password" class="form-control" id="password" placeholder="********" required>
                            </div>
                            <div class="mb-3">
                                <label for="confirm_password" class="form-label ">Confirm Password</label>
                                <input type="password" class="form-control" id="confirm_password" placeholder="********" required>
                            </div>
                            <div class="d-grid">
                                <button class="btn btn-outline-dark" type="submit" id="register_button">Register</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</section>

@section Scripts{
    <script src="~/js/Shared/register.js"></script>
}

ChargingStationWeb/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@using System.Security.Claims
@inject IHttpContextAccessor httpAcc


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ChargingStationWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ChargingStationWeb</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        @if(User.IsInRole("admin")||User.IsInRole("user"))
                        {
                             <li class="nav-item">
                                 <a class="nav-link text-dark" asp-controller="ChargingStations" asp-action="Index">Charging Station</a>
                             </li>
                        }
                        @if (httpAcc.HttpContext.Session.GetString("JWToken") != null && httpAcc.HttpContext.Session.GetString("JWToken").ToString().Length > 0)
                        { 

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Home" asp-action="Logout">Logout</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Home" asp-action="Login">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Home" asp-action="Register">Register</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">      
        <main role="main" class="pb-3">
            @if (TempData["alert"] != null)
            {     
                    <div class="alert @(TempData["alert_type"] as string == "successful"?"alert-success":"alert-danger")  alert-dismissible fade show" role="alert">
                    @TempData["alert"]
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
            }
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.UtcNow.Year - ChargingStationWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script src="https://kit.fontawesome.com/e19c476714.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

ChargingStationWeb/Views/Shared/_LayoutV2.cshtml
@using Microsoft.AspNetCore.Http
@using System.Security.Claims
@inject IHttpContextAccessor httpAcc

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.3.1/dist/leaflet.css" />
    <link rel="stylesheet" href="https://unpkg.com/leaflet.markercluster@1.3.0/dist/MarkerCluster.css" />
    <link rel="stylesheet" href="https://unpkg.com/leaflet.markercluster@1.3.0/dist/MarkerCluster.Default.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <link rel="stylesheet" href="~/css/style.css">
    <link rel="stylesheet" href="~/css/typeahead.css">
    <title>@ViewData["Title"] - ChargingStationWeb</title>
</head>
<body class="d-flex flex-column min-vh-100">
    <!-- Navbar -->
    <nav class="navbar bg-primary navbar-expand-lg fw-bold fixed-top">
        <div class="container">
            <a class="navbar-brand text-light" asp-controller="Home" asp-action="Index"><i class="bi bi-ev-station"></i>ChargingStation</a>
            <button class="navbar-toggler"  type="button" data-bs-toggle="collapse" data-bs-target="#nav-menu"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="nav-menu">
                <ul class="navbar-nav ms-auto">
                    @if (httpAcc.HttpContext.Session.GetString("JWToken") != null && httpAcc.HttpContext.Session.GetString("JWToken").ToString().Length > 0)
                    {
                        <li class="nav-item ">
                            <a class="nav-link text-white" asp-controller="ChargingStations" asp-action="Index">Charging Station</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-controller="Home" asp-action="Logout">Logout</a>
                        </li>
                    }
                    else
                    {
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-controller="Home" asp-action="Login">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-controller="Home" asp-action="Register">Register</a>
                        </li>
                    }                  
                </ul>
            </div>
        </div>
    </nav>

    <!-- Main -->
    @RenderBody()

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <script src="~/js/jquery-3.6.4.js"></script>
    <script src="~/js/typeahead.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <!-- Make sure you put this AFTER Leaflet's CSS -->
    <script src="https://unpkg.com/leaflet@1.3.1/dist/leaflet.js"></script>
    <script src="https://unpkg.com/leaflet.markercluster@1.3.0/dist/leaflet.markercluster.js"></script> 
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>  
    @RenderSection("Scripts", required: false)
</body>
</html>